rollbar/Rollbar.NET

README.md

Double-checked with Andrew after testing issues.

Fixing error level

---

README.md

There are some areas that I have unresolved questions about. I'll comment on the lines.

Updating docs per Andrey.

---

README.md

@akornich Here are the updated docs for the new version

Updating README with blocking docs

---

README.md
Rollbar/AspNetCore/RollbarHttpAttributes.cs
Rollbar/AspNetCore/RollbarLogger.cs
Rollbar/AspNetCore/RollbarMiddleware.cs
Rollbar/RollbarLogger.cs
Sample.NetCore.ConsoleApp/Program.cs
SolutionCommon.csproj
UnitTest.Rollbar/RollbarLoggerFixture.cs

addressed issues: 
#115 
#118 
#119

A bundle for 1.2.1 release  

---

Prototype.RollbarTraceListener/Prototype.RollbarTraceListener.sln
Prototype.RollbarTraceListener/Prototype.RollbarTraceListener/App.config
Prototype.RollbarTraceListener/Prototype.RollbarTraceListener/Program.cs
Prototype.RollbarTraceListener/Prototype.RollbarTraceListener/Properties/AssemblyInfo.cs
Prototype.RollbarTraceListener/Prototype.RollbarTraceListener/Prototype.RollbarTraceListener.csproj
Prototype.RollbarTraceListener/Rollbar.PlugIns/Properties/AssemblyInfo.cs
Prototype.RollbarTraceListener/Rollbar.PlugIns/Rollbar.PlugIns.csproj
Prototype.RollbarTraceListener/Rollbar.PlugIns/RollbarTraceListener.cs
Prototype.RollbarTraceListener/Rollbar.PlugIns/packages.config
README.md
Rollbar/Common/IpAddressUtility.cs
Rollbar/DTOs/Request.cs
Rollbar/IRollbarConfig.cs
Rollbar/IpAddressCollectionPolicy.cs
Rollbar/NetFramework/RollbarConfigSection.cs
Rollbar/PersonDataCollectionPolicies.cs
Rollbar/RollbarConfig.cs
Rollbar/_Rollbar.cd
SolutionCommon.csproj
UnitTest.Rollbar/Common/IpAddressUtilityFixture.cs
UnitTest.Rollbar/DTOs/FrameFixture.cs
UnitTest.Rollbar/DTOs/RequestFixture.cs
UnitTest.Rollbar/DTOs/TraceFixture.cs
UnitTest.Rollbar/NetCore/AppSettingsUtilFixture.cs
UnitTest.Rollbar/NetFramework/RollbarConfigSectionFixture.cs
UnitTest.Rollbar/TestData/app.config
UnitTest.Rollbar/TestData/appsettings.json
UnitTest.Rollbar/UnitTest.Rollbar.csproj

- resolve #128: Only collect person.id by default for person tracking
- resolve #129: Allow IP collection to be easily turned on and off in config
- resolve #130: Anonymize IP address config option
- resolve #135: Simplify/clean-up RollbarConfigSection implementation
- resolve #134: Enhance multi-targeting configuration by introducing NetVariant MSBuild property
- resolve #133: Fix unit tests broken by Visual Studio update v15.7.0
- resolve #121: Add an example/demo of a Rollbar.NET plug-in for a popular .NET logging library
- resolve #122: Update packages of the Samples

Higher priority batch for upcoming Release v1.3.0

---

Rollbar/AspNetCore/RollbarMiddleware.cs
Rollbar/Common/DateTimeUtil.cs
Rollbar/DTOs/Data.cs
Rollbar/DTOs/ExtendableDtoBase.cs
Rollbar/DTOs/NetworkTelemetry.cs
Rollbar/DTOs/Telemetry.cs
Rollbar/Deploys/Deploy.cs
Sample.AspNetCore2.WebApi/appsettings.json
SolutionCommon.csproj
UnitTest.Rollbar/DTOs/ClientFixture.cs
UnitTest.Rollbar/DTOs/DataFixture.cs
UnitTest.Rollbar/DTOs/TelemetryFixture.cs
UnitTest.Rollbar/Telemetry/TelemetryCollectorFixture.cs

- resolve #161: Rollbar Asp.Net Core middleware: auto-capture a NetworkTelemetry event based on the HTTP request processed by the middleware

one more for v1.5.1 release on Monday

---

Rollbar/RollbarLogger.cs
Rollbar/RollbarLoggerBlockingWrapper.cs
UnitTest.Rollbar/RollbarLoggerBlockingWrapperFixture.cs
UnitTest.Rollbar/RollbarLoggerFixture.cs

Fix for #169 
I managed to build it and make my added test pass but I couldn't get make all the other tests pass :(

- resolve #169: Use appropriate LogLevels for convenience methods

---

Rollbar.sln
Rollbar/DTOs/Data.cs
Rollbar/DTOs/ExtendableDtoBase.cs
Rollbar/DTOs/LogTelemetry.cs
Rollbar/DTOs/NetworkTelemetry.cs
Sequential.runsettings
SolutionCommon.csproj
UnitTest.Rollbar/Telemetry/TelemetryCollectorFixture.cs

- resolve #171: Fix some unit tests failing during the unit tests batch run

- resolve #171: Fix some unit tests failing during the unit tests batch run

---

Rollbar/Deploys/RollbarDeployClient.cs
Rollbar/PayloadTruncation/MinBodyTruncationStrategy.cs
Rollbar/RollbarClient.cs
Sample.Xamarin.Forms/Sample.Xamarin.Forms.Android/Sample.Xamarin.Forms.Android.csproj
Sample.Xamarin.Forms/Sample.Xamarin.Forms.UWP/App.xaml.cs
Sample.Xamarin.Forms/Sample.Xamarin.Forms.UWP/Sample.Xamarin.Forms.UWP.csproj
Sample.Xamarin.Forms/Sample.Xamarin.Forms.iOS/Sample.Xamarin.Forms.iOS.csproj
Sample.Xamarin.Forms/Sample.Xamarin.Forms/App.xaml.cs
Sample.Xamarin.Forms/Sample.Xamarin.Forms/Sample.Xamarin.Forms.csproj
SolutionCommon.csproj

Improvements and fixes:
- resolve #173: Unable to use Rollbar with Xamarin.Forms for Android project since version 1.5.1
- ref #153: Not able to get correct traceback (added example of reporting unhandled exceptions from the Xamarin UWP sample app)

v1.5.5 release candidate

---

Rollbar/ErrorLevel.cs
Rollbar/RollbarAssistant.cs
Rollbar/RollbarLogger.cs
Sample.Net.ConsoleApp/GameDomainModel.cs
Sample.Net.ConsoleApp/Program.cs
Sample.Net.ConsoleApp/Sample.Net.ConsoleApp.csproj
Sample.Net.ConsoleApp/_GameDomainModel.cd
SolutionCommon.csproj
UnitTest.Rollbar/RollbarAssistantFixture.cs

- resolve #180: Redo meaning of the log level config setting into logging level threshold
- resolve #179: Improve RollbarAssistant's CaptureState APIs by allowing state capture into existing state bag
- resolve #178: Add example showing local variables
- resolve #181: Update existing documentation regarding new meaning of log level config setting

next release candidate

---

Rollbar/Instrumentation/PerformanceTimer.cs
SolutionCommon.csproj

- resolve #277: Implement all Codacy recommendations after its rules are tuned and configured.
- resolve #276: Analyze, tune Codacy rules and settings for the project's codebase.
- resolve #275: Complete Codacy integration.

Completed basic Codacy integration

---

Rollbar.PlugIns.NLog/RollbarTarget.cs
Rollbar.PlugIns.Serilog/RollbarSinkExtensions.cs
Rollbar/Common/IReconfigurable.cs
Rollbar/DTOs/ExtendableDtoBase.cs
Rollbar/PlugIns/PlugInCore.cs
Rollbar/RollbarAssistant.cs
Rollbar/RollbarQueueController.cs
Rollbar/RollbarResponse.cs
Rollbar/RollbarResult.cs
Rollbar/Telemetry/TelemetryCollector.cs

Improvements and fixes:
- resolve #277: Implement all Codacy recommendations after its rules are tuned and configured.
- resolve #276: Analyze, tune Codacy rules and settings for the project's codebase.
- resolve #275: Complete Codacy integration.
- resolve #266: Create sample for Rollbar.PlugIns.MSEnterpriseLibrary.
- resolve #272: Factor out unit test base that initializes/disposes Rollbar instance and verifies successful transmissions.
- resolve #273: Provide API to check equality of two RollbarConfig objects (property-by-property).
- resolve #271: Factor out shared RollbarUnitTestSettings.
- resolve #270: Setup unit tests for Rollbar.PlugIns.Serilog.
- resolve #269: Setup unit tests for Rollbar.PlugIns.NLog.
- resolve #268: Setup unit tests for Rollbar.PlugIns.Log4net.
- ref #237: …

v2.2.1 release candidate

---

Rollbar/Common/ReconfigurableBase.cs
Rollbar/RollbarConfig.cs
Rollbar/Telemetry/ITelemetryConfig.cs
Rollbar/Telemetry/TelemetryConfig.cs
SolutionCommon.csproj

- resolve #283: ReconfigurableBase&lt;T, TBase&gt;: Override 'Equals(object)'.
- resolve #284: ReconfigurableBase&lt;T&gt;: Override 'Equals(object)'.

implementing Codacy suggestions

---

Rollbar/RollbarLogger.cs
SolutionCommon.csproj

- resolve #296: Out of memory exception with high exceptions rate in multi threaded environment.

- resolve #296

---

Rollbar.Net.AspNet.Mvc/HttpRequestPackageDecorator.cs
Rollbar.Net.AspNet.WebApi/Rollbar.Net.AspNet.WebApi.csproj
Rollbar.Net.AspNet.WebApi/RollbarExceptionFilterAttribute.cs
Rollbar.sln
Rollbar/AspNet/ReadMe.txt
SolutionCommon.csproj
UnitTest.Rollbar.Net.AspNet.Mvc/ExceptionContextPackageFixture.cs
UnitTest.Rollbar.Net.AspNet.Mvc/UnitTest.Rollbar.Net.AspNet.Mvc.csproj
UnitTest.Rollbar.Net.AspNet.WebApi/RollbarExceptionFilterAttributeFixture.cs
UnitTest.Rollbar.Net.AspNet.WebApi/UnitTest.Rollbar.Net.AspNet.WebApi.csproj

Improvements and fixes:
- resolve #322: General codebase cleanup.
- resolve #321: Address latest Codacy review results.
- resolve #320: Update CI build scripts/environment.
- resolve #325: Extract integration with .NET Framework ASP.NET MVC into separate project (Rollbar.Net.AspNet.Mvc).
- resolve #326: Extract integration with .NET Framework ASP.NET Web API into separate project (Rollbar.Net.AspNet.WebApi).

 Release candidate: v3.0.1-preview

---

README.md
ReleaseNotes.md
SdkCommon.csproj

- resolve #340: Add v3 specifics info into "Blocking vs Non-Blocking Use" section of ReadMe.md.
- updated to next release version;
- corrected content/typos of readme.md and releasenotes.md

documentation corrections

---

Rollbar.NetCore.AspNet/LoggingBuilderExtensions.cs
Rollbar.NetCore.AspNet/RollbarMiddlewareException.cs
Rollbar.sln
Rollbar/RollbarLogger.cs
SdkCommon.csproj
UnitTest.Rollbar/DTOs/ClientFixture.cs
UnitTest.Rollbar/RollbarLoggerFixture.cs
azure-pipelines.yml

- resolve #355: AddRollbar() is missing in release 3.0.3

 Fix #355: AddRollbar() is missing in release 3.0.3

---

Rollbar.PlugIns.Log4net/RollbarAppender.cs
Rollbar/PlugIns/PlugInCore.cs
SdkCommon.csproj
UnitTest.Rollbar.PlugIns.Log4net/RollbarAppenderFixture.cs

- resolve #373: Rollbar.PlugIns.Log4net - Make IRollbarConfig API publicly available to the plug-in users

- resolve #373: Rollbar.PlugIns.Log4net

---

Rollbar.NetCore.AspNet/HttpRequestPackageDecorator.cs
Rollbar/DTOs/Request.cs
Rollbar/RollbarClient.cs
Samples/Sample.AspNetCore2.WebApi/Startup.cs
SdkCommon.csproj
UnitTest.Rollbar.PlugIns.Log4net/RollbarAppenderFixture.cs
UnitTest.Rollbar/RollbarClientFixture.cs

- resolve #375: Scrub fields don't appear to be scrubbed within request body's JSON data 
- code cleanup, typo corrections, etc.

Release candidate: v3.0.6

---

Rollbar/DTOs/DtoBase.cs
SdkCommon.csproj

- fix:  resolve #389: Fix failing unit-tests (after recent PR merges)

fix: resolve #389

---

UnitTest.Rollbar/AccessTokenQueuesMetadataFixture.cs

- fix:  resolve #389: Fix failing unit-tests (after recent PR merges)

fix:  resolve #389

---

Rollbar/DTOs/Body.cs
Rollbar/DTOs/CrashReport.cs
Rollbar/DTOs/Data.cs
Rollbar/DTOs/DtoBase.cs
Rollbar/DTOs/Message.cs
Rollbar/DTOs/Payload.cs
Rollbar/DTOs/Person.cs
Rollbar/DTOs/Telemetry.cs
Rollbar/RollbarConfig.cs
SdkCommon.csproj

- refactor: resolve #388: Remove ValidateIt() from DtoBase type and replace its overrides based on IValidatable

refactor: resolve #388

---

Rollbar.Net.AspNet/HttpContextPackageDecorator.cs
Rollbar.Net.AspNet/HttpRequestPackageDecorator.cs
Rollbar.Net.AspNet/HttpResponsePackageDecorator.cs
Rollbar.Net.AspNet/RollbarHttpModule.cs
SdkCommon.csproj

feat:      resolve #418: Rollbar.Net.AspNet: add auto-capture of the current HTTP request/response to RollbarHttpModule.

feat:      resolve #418

---

Rollbar.NetCore.AspNet/HttpRequestPackageDecorator.cs

- ref #415: Rollbar.NetCore.AspNet: Add auto-capture of the current HTTP response by the RollbarMiddleware
- capturing extra metadata about the HTTP request

feat: ref #415

---

Rollbar.Net.AspNet.Mvc/ExceptionContextPackage.cs
Rollbar.Net.AspNet/HttpContextPackageDecorator.cs
Rollbar.Net.AspNet/HttpRequestPackageDecorator.cs
SdkCommon.csproj

feat:      resolve #417: Rollbar.Net.AspNet.Mvc: add auto-capture of the current HTTP response to RollbarExceptionFilter.

feat:      resolve #417

---

Rollbar.Net.AspNet.WebApi/HttpActionContextPackageDecorator.cs
Rollbar.Net.AspNet.WebApi/Rollbar.Net.AspNet.WebApi.csproj
Rollbar.Net.AspNet.WebApi/RollbarExceptionFilterAttribute.cs
SdkCommon.csproj
UnitTest.Rollbar/TestData/appsettings.json

feat:      resolve #416: Rollbar.Net.AspNet.WebApi: add auto-capture of the current HTTP request/response to RollbarExceptionFilterAttribute.OnException(...) handler.

feat:      resolve #416

---

Rollbar/PayloadScrubbing/FormDataStringScrubber.cs
Rollbar/PayloadScrubbing/JsonStringScrubber.cs
Rollbar/RollbarClient.cs
SdkCommon.csproj
UnitTest.Rollbar/PayloadScrubbing/FormDataStringScrubberFixture.cs
UnitTest.Rollbar/TestCase.cs

feat: resolve #432: Add ability to scrub form data like HTTP request/response body.

release candidate v3.5.0

---

UnitTest.Rollbar.PlugIns.Log4net/RollbarAppenderFixture.cs

refactor: resolve #439: Correct failing unit tests to account for payload persistence.

refactor: resolve #439

---

UnitTest.Rollbar.PlugIns.Log4net/RollbarAppenderFixture.cs

refactor: ref #439: Correct failing unit tests to account for payload persistence.

refactor: ref #439

---

Rollbar/ConnectivityMonitor.cs
Rollbar/RollbarClient.cs
Rollbar/RollbarQueueController.cs

feat:     ref #424: Enable Persistence to Maintain Logs while Offline.

feat:     ref #424: Enable Persistence to Maintain Logs while Offline.

---

ReleaseNotes.md
Rollbar/IRollbarConfig.cs
Rollbar/NetFramework/AppConfigUtility.cs
Rollbar/NetFramework/RollbarConfigSection.cs
Rollbar/PayloadStore/StoreContext.cs
Rollbar/RollbarConfig.cs
Rollbar/RollbarLogger.cs
Rollbar/RollbarQueueController.cs
Samples/Sample.WpfApp/App.xaml.cs
Samples/Sample.Xamarin.Forms/Sample.Xamarin.Forms/RollbarHelper.cs
SdkCommon.csproj

feat: resolve #465: StoreContext.sqliteConnectionString is hardcoded.

v3.6.1-beta release candidate

---

Benchmarker.Common/Benchmarker.Common.csproj
Rollbar.NetCore.AspNet/Rollbar.NetCore.AspNet.csproj
Rollbar.PlugIns.Log4net/Rollbar.PlugIns.Log4net.csproj
Rollbar.PlugIns.NLog/Rollbar.PlugIns.NLog.csproj
Rollbar.PlugIns.Serilog/Rollbar.PlugIns.Serilog.csproj
Rollbar/Rollbar.csproj
SdkCommon.csproj
azure-pipelines.yml

fixing CI and adding explicit netstandard2.1 target

---

Rollbar/IRollbarConfig.cs
Rollbar/NetFramework/AppConfigUtility.cs
Rollbar/NetFramework/RollbarConfigSection.cs
Rollbar/RollbarConfig.cs
Rollbar/RollbarQueueController.cs
Rollbar/_RollbarPackagingStrategies.cd
Samples/Sample.NetCore.ConsoleApp/Program.cs
SdkCommon.csproj

release candidate v3.7.0

---

Rollbar/Infrastructure/ConnectivityMonitor.cs
Rollbar/RollbarQueueController.cs
Rollbar/_Rollbar.cd
SdkCommon.csproj
UnitTest.Rollbar/RollbarLoggerFixture.cs

feat: resolve #507: Disable ConnectivityMonitor in case a proxy server custom configuration.

release candidate: v3.9.0

---

Rollbar/IRollbarConfig.cs
Rollbar/Infrastructure/InternalRollbarError.cs
Rollbar/Infrastructure/RollbarClient.cs
Rollbar/NetFramework/AppConfigUtility.cs
Rollbar/NetFramework/RollbarConfigSection.cs
Rollbar/NetFramework/RollbarTelemetryConfigSection.cs
Rollbar/RollbarConfig.cs
Rollbar/RollbarQueueController.cs
Samples/Sample.NetCore.ConsoleApp/Program.cs
SdkCommon.csproj
UnitTest.Rollbar.PlugIns.Log4net/RollbarAppenderFixture.cs
UnitTest.Rollbar/RollbarClientFixture.cs

#522: Make Internal HttpClient's timeout property configurable

Release candidate: v3.11.0

---

Rollbar/Common/RuntimeEnvironmentUtility.cs
Rollbar/DTOs/Notifier.cs
SdkCommon.csproj
UnitTest.Rollbar/DTOs/DataFixture.cs

- feat: resolve #546: Add reporting of LTS releases within payloads (the notifier element).
- chore: resolve #544: Add support for explicit LTS releases of the SDK.

feat: resolve #546, chore: resolve #544

---

Rollbar.Net.AspNet.WebApi/HttpActionContextPackageDecorator.cs
SdkCommon.csproj

> Description here
> Fix [#554 ](https://github.com/rollbar/Rollbar.NET/issues/554)

fix: resolve #554

---

Rollbar.Deploys/Properties/AssemblyInfo.cs
Rollbar.Deploys/Rollbar.Deploys.csproj
Rollbar.OfflinePersistence/PayloadStore/Destination.cs
Rollbar.OfflinePersistence/PayloadStore/PayloadRecord.cs
Rollbar.OfflinePersistence/PayloadStore/StoreContext.cs
Rollbar.OfflinePersistence/PayloadStore/_PayloadStore.cd
Rollbar.OfflinePersistence/PayloadStoreRepository.cs
Rollbar/Infrastructure/AccessTokenQueuesMetadata.cs
Rollbar/Infrastructure/PayloadQueue.cs
Rollbar/Infrastructure/RollbarClient.cs
Rollbar/Infrastructure/RollbarLoggerBlockingWrapper.cs
Rollbar/PayloadScrubbing/FormDataStringScrubber.cs
Rollbar/PayloadScrubbing/RollbarPayloadScrubber.cs
Rollbar/PayloadStore/IDestination.cs
Rollbar/PayloadStore/IPayloadRecord.cs
Rollbar/PayloadStore/IPayloadStoreRepository.cs
Rollbar/PayloadStore/PayloadStoreConstants.cs
Rollbar/PayloadStore/PayloadStoreRepositoryHelper.cs
Rollbar/PayloadStore/_PayloadStore.cd
Rollbar/Rollbar.csproj
Rollbar/RollbarFactory.cs
Rollbar/RollbarLogger.cs
Rollbar/RollbarQueueController.cs
Rollbar/Serialization/Json/JsonScrubber.cs
Rollbar/Telemetry/TelemetryCollector.cs
Rollbar/Telemetry/TelemetryQueue.cs
SdkCommon.csproj

> Description here
> resolve #559 
> resolve #529 
> resolve #528
> resolve #523  
> resolve #498 
> resolve #485

Offline persistence (follow-up)

---

README.md

> v3-to-v4 upgrade instructions
> n/a

Update README.md: v3-to-v4 upgrade instructions

---

README.md
SdkCommon.csproj

> Updated README.md with v5-beta announcement
> n/a

Updated README.md with v5-beta announcement

---

README.md
Rollbar/Common/Validator.cs
Rollbar/Infrastructure/RollbarLogger.cs
Rollbar/Infrastructure/RollbarSingleThreadedLogger.cs
Rollbar/RollbarException.cs
Rollbar/RollbarInfrastructure.cs
SdkCommon.csproj

> feat: resolve #408 - Invalid configuration file prototype error
> #408

feat: resolve #408 - Invalid configuration file prototype error

---

Benchmarker.Common/Benchmarker.Common.csproj
Rollbar.Deploys/Rollbar.Deploys.csproj
Rollbar/Rollbar.csproj
SdkCommon.csproj
UnitTest.Rollbar.App.Config/UnitTest.Rollbar.App.Config.csproj
UnitTest.Rollbar.AppSettings.Json/UnitTest.Rollbar.AppSettings.Json.csproj
UnitTest.Rollbar.Deploys/UnitTest.Rollbar.Deploys.csproj
UnitTest.Rollbar.Net.AspNet.Mvc/UnitTest.Rollbar.Net.AspNet.Mvc.csproj
UnitTest.Rollbar.Net.AspNet.WebApi/UnitTest.Rollbar.Net.AspNet.WebApi.csproj
UnitTest.Rollbar.NetPlatformExtensions/UnitTest.Rollbar.NetPlatformExtensions.csproj
UnitTest.Rollbar.OfflinePersistence/UnitTest.Rollbar.OfflinePersistence.csproj
UnitTest.Rollbar.PlugIns.Log4net/UnitTest.Rollbar.PlugIns.Log4net.csproj
UnitTest.Rollbar.PlugIns.MSEnterpriseLibrary/UnitTest.Rollbar.PlugIns.MSEnterpriseLibrary.csproj
UnitTest.Rollbar.PlugIns.NLog/UnitTest.Rollbar.PlugIns.NLog.csproj
UnitTest.Rollbar.PlugIns.Serilog/UnitTest.Rollbar.PlugIns.Serilog.csproj
UnitTest.Rollbar/UnitTest.Rollbar.csproj
UnitTest.RollbarTestCommon/UnitTest.RollbarTestCommon.csproj

> Updated and consolidated Newtonsoft and unit test related dependencies
> #587

Updated and consolidated Newtonsoft and unit test related dependencies

---

README.md
Rollbar.App.Config/RollbarConfigSection.cs
Rollbar.NetCore.AspNet/RollbarMiddleware.cs
Rollbar/Config/RollbarDeveloperOptions.cs
Rollbar/Config/RollbarLoggerConfig.cs
Rollbar/IRollbarDeveloperOptions.cs
SdkCommon.csproj

>  feat: resolve #532 - Make RollbarMiddlewareException wrapper optional based on config settings
> #532

- feat: resolve #532

---

.github/workflows/CI.yml
README.md
UnitTest.Rollbar.App.Config/UnitTest.Rollbar.App.Config.csproj
UnitTest.Rollbar.AppSettings.Json/UnitTest.Rollbar.AppSettings.Json.csproj
UnitTest.Rollbar.OfflinePersistence/UnitTest.Rollbar.OfflinePersistence.csproj

> Resolve #616 
> Resolve #617 
- Resolve #616 
- Resolve #617

Addressing a dependabot alert and CI pipeline fix

---

SdkCommon.csproj

> ref #611 - updated release notes
- Ref #611

ref #611 - updated release notes

---

Rollbar/IRollbarConnectivityMonitor.cs
Rollbar/Infrastructure/RollbarConnectivityMonitor.cs
Rollbar/Infrastructure/_Infrastructure.cd
Rollbar/_RollbarInfrastructure.cd
SdkCommon.csproj
UnitTest.Rollbar/Infrastructure/RollbarConnectivityMonitorFixture.cs

> fix: resolve GH #615 - ConnectivityMonitor tests wrong thing
- Fix #615

fix: resolve GH #615 - ConnectivityMonitor tests wrong thing

---

Rollbar/Common/EmptyDisposable.cs
Rollbar/Infrastructure/RollbarConnectivityMonitor.cs
Rollbar/Infrastructure/RollbarQueueController.cs
Rollbar/Infrastructure/_RollbarPackages.cd
Rollbar/RollbarDataScrubbingHelper.cs
Rollbar/RollbarInfrastructure.cs
Rollbar/RollbarLocator.cs
Rollbar/Telemetry/RollbarTelemetryCollector.cs
Rollbar/Telemetry/_Telemetry.cd
Rollbar/_Rollbar.cd
Rollbar/_RollbarConfig.cd
Rollbar/_RollbarInfrastructure.cd
Rollbar/_RollbarLogger.cd
Rollbar/_RollbarPackagingStrategies.cd
Samples/Sample.VBNet.ConsoleApp/App.config
Samples/Sample.VBNet.ConsoleApp/My Project/Resources.Designer.vb
Samples/Sample.VBNet.ConsoleApp/My Project/Settings.Designer.vb
SdkCommon.csproj

> fix: resolve #623 - NullReference exception while initializing RollbarInfrastructure
\- Fix #623

Hot fix: resolve #623 - NullReference exception while initializing RollbarInfrastructure

---

Rollbar/Config/RollbarPayloadAdditionOptions.cs
Rollbar/DTOs/Data.cs
Rollbar/IRollbarPayloadAdditionOptions.cs
SdkCommon.csproj

feat: resolve #630

---

SdkCommon.csproj

> Please include a summary of the change and which issues are fixed.
> Please also include relevant motivation and context.
n/a

Update project metadata.
